name = "tss-wrangler"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "dfd716443bca4859850dd27a6f885a60"
workers_dev = true
kv_namespaces = [
   { binding = "META", id = "239e6a0c4c8d47569eb202278fd99e58" },
   { binding = "TX_FUNCTIONS", id = "bb7ba59b38e040bbab7d71dfdb826911" },
]
vars = { STELLAR_NETWORK = "TESTNET", TURRET_ADDRESS = "GDD4PR3ZYXM63JWWSIRQ4UAOZ7PM336P5GSXCRYQKAP7AUOWCNCENXVT", TURRET_RUN_URL = "https://h9xfbbzuod.execute-api.us-east-1.amazonaws.com" }