name = "tss-wrangler"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "67d7d17573b7f6732e32f3c0752e0275"
zone_id = "aa6f3497d7e8b5a16e809b8a680fdb33"
workers_dev = true
kv_namespaces = [
   { binding = "META", id = "8456302f5be04b0cb470df5099f92530" },
   { binding = "TX_FUNCTIONS", id = "a490d3557d7c487595465cbfd5d2f7c5" },
   { binding = "TX_FEES", id = "7705f1c377f6466fa74e46c474c05a66" },
   { binding = "TX_SPONSORS", id = "8a6c6710363f4aabae6fd788cd80e5e5" }
]
vars = { STELLAR_NETWORK = "TESTNET", TURRET_ADDRESS = "GDZACR7XAJWU3JLJ5TVDOLCVB5DCIY2K7PHDR7ODGCEQTNVENOPHLCF7", TURRET_RUN_URL = "https://najfh4yqje.execute-api.us-east-1.amazonaws.com" }