org: atemosta
app: tss-serverless
component: express
name: tss-serverless

inputs:
  src:
    src: ./
    # hook: npm run build
    # dist: ./
    exclude: node_modules/**
  memory: 256
  timeout: 8
  env:
    turretBaseUrl: https://tss-wrangler.atemosta.workers.dev 
    turretAddress: GDZACR7XAJWU3JLJ5TVDOLCVB5DCIY2K7PHDR7ODGCEQTNVENOPHLCF7
