name: Deploy Serverless

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: sudo apt-get install -y libsodium-dev
      - run: sudo npm install -g node-gyp

      - name: Deploy to AWS with Serverless
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SERVICE_ROOT: serverless
